### ISSUE TITLE
NVD quits its legacy data feeds by September 2023

### ISSUE THREAD

**Issue by 28seconds** [vulsio/go-cpe-dictionary#88]
NVD seems to quit its legacy data feeds by September 2023.
https://nvd.nist.gov/vuln/data-feeds

<img width="1194" alt="スクリーンショット 2022-10-15 15 55 23" src="https://user-images.githubusercontent.com/115864467/195980994-8757114f-56d2-4ed6-afef-52b3a70f0ad1.png">

How should we face it? 

Maybe it's easy to replace Fetcher > nvd.go ’s function below 
```
func makeFeedURLBlocks(years []int) (urls []string) {
	formatTemplate := "https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz"
	for _, year := range years {
		urls = append(urls, fmt.Sprintf(formatTemplate, year))
	}
	return urls
}
```
To the function to produce corresponnding API  such as 
https://services.nvd.nist.gov/rest/json/cves/2.0/?lastModStartDate=%d-01-01T00:00:00.000%2B01:00&lastModEndDate=%d-12-31T23:59:59.000%2B01:00

But I’m not sure whether this is a good solution.
My concern is about performance.
Does anybody have a good idea?

**Comment by jbmaillet** [comment]
I opened a similar issue on go-cve-dictionary in last August:
https://github.com/vulsio/go-cve-dictionary/issues/272
(And I'll cross-reference it to this one.)

Another hack that I though of would be to download the complete CVE dictionary from MITRE, and then query the CVE one by one since this dictionary as no modified date information.

Your idea, though I'd agree this is not a good solution for performance reason, is still way better then mine! ;-)

_What would really help is to understand WHY? What's the idea behind this change at the NVD?_ Because as I see it, it can only lead to a beautiful disaster: more CPU and bandwidth load on their side, with people using dirty tricks to still get a full and up-to-date replication. The only motivation seems to be "hey,APIs are the way do to it now". As I see it, the feeds with their timestamps metadata are fine and simple.

(To be complete regarding this: I would not be so surprise if it fails and is never talked about again. For example in 2019, SWIDs were supposed to replace CPEs entirely in the NVD. Fasten your seat belts and... we've never heard of that since, not even a post mortem explanation.)

**Comment by 28seconds** [comment]
Thank you for your reaction and letting me know there's a same effect on go-cve-dictionary.

>I would not be so surprise if it fails and is never talked about again

Good point.  It might be better not to rush on this topic and wait until 4-5 months before the limit...
At least, simply replacing current function as what I wrote looks not that hard.  

(As for API, I wasn't aware of 120 days range limitation and pagenation.
Thank you again for your comment on go-cve-dictionary!)

**Comment by jbmaillet** [comment]
Another point that may be more urgent, and even maybe could clash with this "API only" thing on the NVD and possibly delay it is that CVE will upgrade to JSON schema v5.0 by the Fall / end of the year.

This CVE JSON schema v5.0 is now in release candidate 8:
[https://github.com/CVEProject/cve-schema/tags](https://github.com/CVEProject/cve-schema/tags)
It has already been tested several times on the full set of now 180,000+ CVE to ensure that no data is lost, and is now undergoing deployment, see [CVE Board Meeting Notes from October the 12th](https://cve.mitre.org/community/board/meeting_summaries/12_October_2022.pdf).

I'm not a 100% sure the industry can absorb 2 such big changes at such a pace. It's been 2 years this work on the new JSON started, and I'm not sure that many players are ready for this or even started testing for it. While I'm at it, I will open a ticket about it

**Comment by jbmaillet** [comment]
Regarding CVE JSON schema: v5.0 it's just been officially released 1 hour ago.
I created an enhancement ticket on go-cve-dictionary: https://github.com/vulsio/go-cve-dictionary/issues/287

**Comment by jbmaillet** [comment]
Latest news here:
https://github.com/vulsio/go-cve-dictionary/issues/272#issuecomment-1402066491
...and these are not good news.
